config:
  aws:defaultTags:
    tags:
      Service: aimp
      Environment: oss-test
  aws:region: ap-northeast-2
  aimp:AccountId: <AWS Account ID>
  aimp:Env: oss-test
  aimp:ResourceTimeout: 5m
  aimp:DefaultPrefix: aimp
  aimp:ApiVersion: oss-test

  #######################################
  ##### Global Lambda Configuration #####
  #######################################

  aimp:DefaultLambdaTimeout: 30
  aimp:DefaultLambdaStorageSizeMB: 4096
  aimp:DefaultLambdaMemorySizeMB: 4096
  aimp:CommandControllerTimeout: 600
  aimp:LogRetentionInDays: 7
  aimp:LambdaLogFormat: JSON
  aimp:LambdaApplicationLogLevel: INFO
  aimp:LambdaSystemLogLevel: INFO

  aimp:WalPayloadSizeThreshold: 65536
  aimp:BulkUpsertSizeLimitMb: 200

  aimp:QueryExecutorQualifier: QueryExecutor
  aimp:CommandControllerQualifier: CommandController
  aimp:IndexRefresherQualifier: IndexRefresher
  aimp:RequestControllerQualifier: RequestController
  aimp:QueryControllerQualifier: QueryController

  aimp:FsTempPath: /tmp
  aimp:MaxNumComputeNodesStd: 2
  aimp:MaxNumComputeNodesIa: 2
  aimp:DesiredMemoryToStorageRatioStd: 0.5
  aimp:DesiredMemoryToStorageRatioIa: 0.1
  aimp:MemorySizePerComputeNodeStd: 10240
  aimp:MemorySizePerComputeNodeIa: 10240

  #######################################
  ##### BATCH Configuration ############
  #######################################
  aimp:IndexBuilderTimeout: 604800
  aimp:IndexBuildInterval: 60
  aimp:IndexBuilderRetryAttempts: 2
  aimp:IndexBuilderStorageSizeGB: 21
  aimp:IndexBuilderMaxComputeVcpus: 160
  aimp:IndexBuilderVcpu: 8
  aimp:IndexBuilderMemorySizeMB: 16384 # 16GB
  aimp:IndexBuilderJobNamePrefix: IndexBuild
  aimp:IndexBuilderConcurrency: 4
  aimp:IndexBuilderLocalPath: ../../build/libs/indexBuilder
  aimp:IndexBuilderDockerFilePath: ../../Dockerfile

  #######################################
  ##### Deployment Configuration ########
  #######################################
  aimp:FunctionLocalPath: ../../build/distributions/aimp.zip
  aimp:FunctionS3Key: aimp.zip

  #######################################
  ###### S3 Bucket Configuration ########
  #######################################

  # one of the following: private, public-read, public-read-write
  aimp:S3Acl: private
  aimp:S3TempBucketLifecycleRuleInDays: 14

  #######################################
  ###### DynamoDB Configuration ########
  #######################################
  aimp:DynamoDBDefaultBillingMode: pay_per_request

  #######################################
  ###### SQS Configuration ##############
  #######################################
  aimp:SQSVisibilityTimeoutSeconds: 2400

  #######################################
  ###### Scheduler Configuration ########
  #######################################
  aimp:SchedulerMaximumEventAgeInSeconds: 21600
  aimp:SchedulerMaximumRetryAttempts: 2